### ISSUE TITLE
Error on load.

### ISSUE THREAD

**Issue by mgifford** [forsti0506/a11y-sitechecker#262]
I'm not sure why I would be getting this error when attempting to instal this.

```
$ a11y-sitechecker --config=config.json -T=1000
SyntaxError: Unexpected token e in JSON at position 0 
undefined:1
export interface Config {
^

SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at setupConfig (/home/mike/a11y-sitechecker/node_modules/a11y-sitechecker/lib/utils/setup-config.js:40:35)
    at defaultFunction (/home/mike/a11y-sitechecker/node_modules/a11y-sitechecker/bin/a11y-sitechecker_code.js:22:51)
    at /home/mike/a11y-sitechecker/node_modules/a11y-sitechecker/bin/a11y-sitechecker.js:5:64
    at Object.<anonymous> (/home/mike/a11y-sitechecker/node_modules/a11y-sitechecker/bin/a11y-sitechecker.js:5:67)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```

**Comment by forsti0506** [comment]
hi, Can you show me your config.json?
